FROM maven:3.6.3-jdk-11-slim AS build
COPY src ./app/src
COPY pom.xml ./app
RUN mvn -f ./app/pom.xml clean package

FROM openjdk:11
#FROM java:8
#FROM openjdk:8-jre-slim


#WORKDIR D:
#ADD target
COPY --from=build target/master-0.0.1-SNAPSHOT.jar master-0.0.1-SNAPSHOT.jar
EXPOSE 8081
ENTRYPOINT ["java","-Xms2048m","-Xmx7168m", "-jar", "master-0.0.1-SNAPSHOT.jar"]

